honeybadger:
  # Placeholders:
  # %vl%  the current check vl
  # %check% the check for what the player failed
  # %type%  the type of the check for what the player failed
  # %exp% if the check is experimental or not
  # %probability% the chance for the player to cheat
  # %player% the presumed cheater
  alert-message: "&cHBAC &7// &f%player% &7flagged &7%exp% &f%check% &7(%type%)&8 (&cvl: &d%vl% &cProbabilty:&d %probabilty%&7&8)"
  punish-command: "kick %player% &cHBAC &7/ Cheating"

checks:
  aim:
    a:
      enabled: true
      punish: true
      punish-vl: 10
    b:
      enabled: true
      punish: true
      punish-vl: 25
    c:
      enabled: true
      punish: true
      punish-vl: 25
  autoclicker:
    a:
      enabled: true
      punish: true
      punish-vl: 10
  killaura:
    a:
      enabled: true
      punish: true
      punish-vl: 10
    b:
      enabled: true
      punish: true
      punish-vl: 25
    c:
      enabled: true
      punish: true
      punish-vl: 10
    d:
      enabled: true
      punish: true
      punish-vl: 25
    e:
      enabled: true
      punish: true
      punish-vl: 10
  reach:
    a:
      enabled: true
      punish: true
      punish-vl: 10
  ground:
    a:
      enabled: true
      punish: true
      punish-vl: 10
  timer:
    a:
      enabled: true
      punish: true
      punish-vl: 10
  flight:
    a:
      enabled: true
      punish: true
      punish-vl: 10
    b:
      enabled: true
      punish: true
      punish-vl: 25
    c:
      enabled: true
      punish: true
      punish-vl: 10
  jump:
    a:
      enabled: true
      punish: true
      punish-vl: 10
  speed:
    a:
      enabled: true
      punish: true
      punish-vl: 10
  step:
    a:
      enabled: true
      punish: true
      punish-vl: 10