honeybadger:
  # Placeholders:
  # %vl%  the current check vl
  # %check% the check for what the player failed
  # %type%  the type of the check for what the player failed
  # %exp% if the check is experimental or not
  # %probability% the chance for the player to cheat
  # %player% the presumed cheater
  alert-message: "&cHBAC &7// &f%player% &7flagged &7%exp% &f%check% &7(%type%)&8 (&cvl: &d%vl% &cProbabilty:&d %probabilty%&7&8)"
  punish-command: "kick %player% &cHBAC &7/ Cheating"
  punish-vl: 15
